"""First migration

Revision ID: f1627fb35393
Revises: 
Create Date: 2023-12-24 14:05:23.780993

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f1627fb35393'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id',
                              fastapi_users_db_sqlalchemy.generics.GUID(),
                              nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024),
                              nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('shorturl',
                    sa.Column('user_id',
                              fastapi_users_db_sqlalchemy.generics.GUID(),
                              nullable=True),
                    sa.Column('short_url', sa.String(length=5), nullable=True),
                    sa.Column('original_url', sa.String(length=300),
                              nullable=True),
                    sa.Column('type', sa.String(length=10), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                            name='user_created_short_url'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('short_url')
                    )
    op.create_table('clickurl',
                    sa.Column('access_time', sa.DateTime(), nullable=True),
                    sa.Column('url_id',
                              fastapi_users_db_sqlalchemy.generics.GUID(),
                              nullable=True),
                    sa.Column('user_id',
                              fastapi_users_db_sqlalchemy.generics.GUID(),
                              nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['url_id'], ['shorturl.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                            name='user_click_on_url'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clickurl')
    op.drop_table('shorturl')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
